### ISSUE TITLE
What is the purpose of `eps` in GeM layer?

### ISSUE THREAD

**Issue by WarBean** [facebookresearch/multigrain#5]
I notice that the [GeM layer](https://github.com/facebookresearch/multigrain/blob/master/multigrain/modules/functional.py#L30) use `eps` to clamp the input feature maps, but I cannot find any corresponding description in the original paper.

Nevertheless, I directly plug this eps-clamped GeM layer into my own network and it finally improve the performance.  However, I still don't understand the utility of eps-clamping, and wonder how GeM performs differently in your experiments w/o this trick?

**Comment by alup** [comment]
I suppose that, as it is a common practice, `eps` term is added to improve numerical stability and avoiding inf or zero gradients etc.

**Comment by bermanmaxim** [comment]
Thank you @alup, that is it; moreover we followed the implementation of https://github.com/filipradenovic/cnnimageretrieval-pytorch.
