### ISSUE TITLE
Image retrieve

### ISSUE THREAD

**Issue by xiaer1** [facebookresearch/multigrain#7]
how can I use dataset:UKBench for train, Should I modify the `IN1K` in `train.py` ? as follows:
  transforms = get_transforms(IN1K, args.input_size, args.augmentation, args.backbone)
    datas = {}
    for split in ('train', 'val'):
        imload = preloader(args.imagenet_path, args.preload_dir_imagenet) if args.preload_dir_imagenet else default_loader
        datas[split] = IdDataset(IN1K(args.imagenet_path, split, transform=transforms[split], loader=imload))

that is,write the same file as `imagenet.py`

**Comment by bermanmaxim** [comment]
See https://github.com/facebookresearch/multigrain/issues/6#issuecomment-510577255.
